import{a as y,S as h,i as P}from"./assets/vendor-b42c18af.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();function v({webformatURL:r,largeImageURL:s,tags:a,likes:o,views:e,comments:t,downloads:n}){return` 
  <a href="${s}" class="gallery-link">
     <figure>
      <img src="${r}" alt="${a}" class="gallery-image">
      <figcaption class="gallery-figcaption">
        <div class="image-item">Likes <span class="image-elem">${o}</span></div>
        <div class="image-item">Views <span class="image-elem">${e}</span></div>
        <div class="image-item">Comments <span class="image-elem">${t}</span></div>
        <div class="image-item">Downloads <span class="image-elem">${n}</span></div>
  </figcaption>
  </figure>
</a >`}function S(r){return r.map(v).join("")}class ${constructor(){}async getPictures(s,a){const o="https://pixabay.com/api",e="/?key=42190673-143cbde4cd6a94de75e31d0a4",t="&image_type=photo&orientation=horizontal&safesearch=true",n="&per_page=15",p="&page=",g=`&q=${s}`,f=`${o}${e}${g}${t}${n}${p}${a}`,m=await y.get(f);return console.log("Запит на сервер",m.data),m.data}}const F=new $,c=document.querySelector(".form-search"),l=document.querySelector(".gallery"),i=document.querySelector(".loader-container"),u=document.querySelector(".js-load-btn");i.style.display="none";u.style.display="none";c.addEventListener("submit",L);let d=1;async function L(r){r.preventDefault();const s=r.target.elements.text.value.trim();if(s===""){l.innerHTML="";return}l.innerHTML="",i.style.display="flex";const{total:a,hits:o}=await F.getPictures(s,d);if(o.length===0){A(),c.reset(),i.style.display="none";return}l.innerHTML=S(o),new h(".gallery a",{captionDelay:250,captionsData:"alt",showCounter:!1}),c.reset(),i.style.display="none",u.style.display="block"}u.addEventListener("submit",b);function b(r){r.preventDefault(),d+=1,console.log("hello")}function A(){P.show({close:!0,message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",messageSize:"10px",backgroundColor:"#B51B1B",position:"topRight",close:!0,timeout:1e4,progressBarColor:"#FFFFFF",maxWidth:"380px"})}
//# sourceMappingURL=commonHelpers.js.map
