import{i as p,a as C,S as b}from"./assets/vendor-483db976.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const u={formEl:document.querySelector(".form-search"),imgContainer:document.querySelector(".gallery"),loaderContainer:document.querySelector(".loader-container"),loaderBtn:document.querySelector(".js-load-btn")};function A({webformatURL:r,largeImageURL:o,tags:s,likes:a,views:e,comments:t,downloads:n}){return` 
  <a href="${o}" class="gallery-link">
     <figure>
      <img src="${r}" alt="${s}" class="gallery-image">
      <figcaption class="gallery-figcaption">
        <div class="image-item">Likes <span class="image-elem">${a}</span></div>
        <div class="image-item">Views <span class="image-elem">${e}</span></div>
        <div class="image-item">Comments <span class="image-elem">${t}</span></div>
        <div class="image-item">Downloads <span class="image-elem">${n}</span></div>
  </figcaption>
  </figure>
</a >`}function h(r){const o=r.map(A).join("");u.imgContainer.insertAdjacentHTML("beforeend",o)}const{loaderBtn:y,loaderContainer:F}=u;function L(){F.classList.remove("hidden")}function l(){F.classList.add("hidden")}function B(){y.classList.remove("hidden")}function E(){y.classList.add("hidden")}function x(){p.show({close:!0,message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",messageSize:"10px",backgroundColor:"#B51B1B",position:"center",close:!0,timeout:1e4,progressBarColor:"#FFFFFF",maxWidth:"380px"})}function q(){p.show({close:!0,message:"We are sorry, but you have reached the end of search results",messageColor:"#FFFFFF",messageSize:"10px",backgroundColor:"#004ff9c7",position:"bottomCenter",close:!0,timeout:1e4,progressBarColor:"#FFFFFF",maxWidth:"380px"})}class M{constructor(){}async getPictures(o,s,a){const e="https://pixabay.com/api",t="/?key=42190673-143cbde4cd6a94de75e31d0a4",n="&image_type=photo&orientation=horizontal&safesearch=true&per_page=",S="&page=",$=`&q=${o}`,w=`${e}${t}${$}${n}${a}${S}${s}`,f=await C.get(w);return console.log("Запит на сервер",o,s,f.data),f.data}}const{formEl:d,imgContainer:g,loaderBtn:H}=u,P=new M;let i;const m=15;let c="";d.addEventListener("submit",O);async function O(r){if(r.preventDefault(),c=r.target.elements.text.value.trim(),c===""){g.innerHTML="";return}g.innerHTML="",L(),i=1;const{totalHits:o,hits:s}=await P.getPictures(c,i,m);if(s.length===0){x(),d.reset(),l();return}h(s),new b(".gallery a",{captionDelay:250,captionsData:"alt",showCounter:!1}),d.reset(),l(),v(o)}H.addEventListener("click",R);async function R(){i+=1,L(),E();const{totalHits:r,hits:o}=await P.getPictures(c,i,m);h(o),l(),v(r)}function v(r){i<=r/m?B():q()}
//# sourceMappingURL=commonHelpers.js.map
